package com.cosek.edms.managers;

import com.cosek.edms.teams.Team;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDate;
import java.util.List;

@Entity
@Data
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Manager {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // now auto-generated by DB

    private String name;
    private String nationality;
    private int age;
    private String image;
    private int experience;

    @ElementCollection
    private List<String> achievements;

    private String tacticalStyle;
    private LocalDate contractStart;
    private LocalDate contractEnd;

    @Enumerated(EnumType.STRING)
    private ManagerRole role;

    private String specialization; // Optional: only for assistants

    @ManyToOne(fetch = FetchType.LAZY)
    private Team clubTeam;

    @ManyToOne(fetch = FetchType.LAZY)
    private Team nationalTeam;
}
