version: "3.8"

services:
  warehouse-backend:
    image: trevorsimon/coseke_warehouse_backend:latest
    container_name: coseke_warehouse_backend
    ports:
      - "8080:8080"  # Exposing backend on port 8080
    networks:
      - warehouse-network

networks:
  warehouse-network:
    driver: bridge
